### PR TITLE
Add initial user and developer documentation

### PR DESCRIPTION
**Pull request by afutofu**
### Description
Add initial user and developer documentation according to the [Documentation Spec](https://courses.cs.washington.edu/courses/cse403/24au/project/06_documentation.html).

### List of changes
- Add user documentation according to spec
- Add developer documentation according to spec

### Did you install additional dependencies?
- [ ] Yes

### Which part of the repository does your PR affect?
- [ ] Sign In
- [ ] Sign Up
- [ ] Onboarding
- [ ] Profile
- [ ] Workout
- [ ] Quest
- [ ] Shop
- [ ] Social
- [ ] Project Structure
- [x] Other. If so, specify: Documentation

### CODE REVIEW

**Review by ArcaneLG — APPROVED** [review]
Everything looks ok to me. Maybe, for the user installation guide, we should add some alternate way to the play store for now since we don't have the app there yet? That's the only possible concern, but it's not a big deal.

**Comment by afutofu** [comment]
@ArcaneLG Yeah you're right. I was thinking the same thing. Any ideas on what we should write as an alternative?

@Dominic-Roser @Prayug @adamben04 @ColinDao

**Comment by ArcaneLG** [comment]
Probably just instructions to get the repo right? Is there any other way?

**Comment by afutofu** [comment]
Alright. I'll make those changes

**Comment by afutofu** [comment]
Changes made. I will merge this PR. Future changes to the docs will be made in subsequent PRs

**Pull request merged**
